### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by PySimpleGUI** [Aron-HD/CMS-bot-GUI#1]
Hiya

It looks you've got a nice GUI, but don't know for sure as I've not installed everything.  I've found that projects with a GUI that have screenshots in their readme get a lot more attention.  People love seeing pictures.  They're easy to add.  The  way I do it is to add an image to an Issue, just like this Issue, and then copy / paste the code that is generated into my readme.md file.  It's a trivial way to host images without actually putting them into your project folders.

**Comment by Aron-HD** [comment]
Thanks for the tip :) I'll certainly add some pictures this week.

**Comment by Aron-HD** [comment]
![cms-bot-bullets](https://user-images.githubusercontent.com/60329603/79757653-4b0dc680-8314-11ea-8166-80084a982523.JPG)
![cms-bot-metadata1](https://user-images.githubusercontent.com/60329603/79757671-4fd27a80-8314-11ea-8895-8a4301e7bd0c.JPG)
![cms-bot-metadata2](https://user-images.githubusercontent.com/60329603/79757673-506b1100-8314-11ea-95dd-f3892f4deed3.JPG)

**Comment by PySimpleGUI** [comment]
Ooooooooo..... I like it!

Very nicely done!  Now everyone can _appreciate_ what you've built, even if they never install it.  It's great to see what you've done.
